---
- name: Run apt update
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 1800
  when: ansible_os_family == "Debian"
  tags:
    - apt

- name: Install Debian family packages
  become: true
  ansible.builtin.apt:
    name: ['acl', 'apt-transport-https', 'ca-certificates', 'curl',
           'dbus-user-session', 'gnupg', 'iptables', 'libpam-systemd',
           'lsb-release', 'python3-pexpect', 'python3-pip', 'python3-six',
           'slirp4netns', 'uidmap']
    state: present
    install_recommends: false
  when: ansible_os_family == "Debian"
  tags:
    - acl
    - apt
    - packages
    - gidmap

- name: Install RedHat family packages
  become: true
  ansible.builtin.dnf:
    name: ['curl', 'iptables', 'python3-pip']
    state: present
  when: ansible_os_family == "RedHat"
  tags:
    - dnf
    - packages

- name: Install RedHat family slirp4netns
  become: true
  ansible.builtin.dnf:
    name: 'slirp4netns'
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution != "Amazon"
  tags:
    - dnf
    - packages

- name: Install slirp4netns binary
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/rootless-containers/slirp4netns/releases/download/v1.2.0/slirp4netns-{{ansible_architecture}}"
    dest: /usr/bin/slirp4netns
    checksum: "sha256:{{hashes["slirp4netns-"{{ansible_architecture}}]}}"
    owner: root
    group: root
    mode: '0755'
  when: ( ansible_distribution == "Amazon" ) or ( ansible_distribution_version == "18.04" )
  tags:
    - dnf
    - packages

- name: Install fuse-overlayfs
  become: true
  ansible.builtin.apt:
    name: fuse-overlayfs
    state: present
    install_recommends: false
  when: >
    ansible_distribution == "Debian" and
    (ansible_kernel is version("4.18", ">=") and
    ansible_kernel is version("5.11", "<="))
  tags:
    - apt
    - packages

- name: Python3-rpm installation
  become: true
  ansible.builtin.dnf:
    name: "python3-rpm"
    state: present
  when: ansible_distribution == "RedHat"
  tags:
    - dnf
    - yum
    - packages

- name: Install python3 setuptools
  become: true
  ansible.builtin.dnf:
    name: "python3-setuptools"
    state: present
  when: ansible_distribution == "AlmaLinux"
  tags:
    - dnf
    - packages

- name: Install python3 docker
  become: true
  ansible.builtin.pip:
    name: docker
    state: present
  tags:
    - docker
    - python

- name: Sysctl net.ipv4.ip_forward
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true
    state: present
    reload: true
  tags:
    - sysctl

- name: Sysctl kernel.unprivileged_userns_clone
  become: true
  ansible.posix.sysctl:
    name: kernel.unprivileged_userns_clone
    value: "1"
    sysctl_set: true
    state: present
    reload: true
  when: ansible_distribution == "Debian" and
        ansible_distribution_version is version('11', '<')
  tags:
    - sysctl

- name: Sysctl net.ipv4.ip_unprivileged_port_start=0
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: "0"
    sysctl_set: true
    state: present
    reload: true
  when: docker_allow_privileged_ports
  tags:
    - sysctl

- name: Sysctl net.ipv4.ping_group_range=0 2147483647
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ping_group_range
    value: "0 2147483647"
    sysctl_set: true
    state: present
    reload: true
  when: docker_allow_ping
  tags:
    - sysctl

- name: Load the overlay module
  become: true
  community.general.modprobe:
    name: overlay
    state: present
    params: 'permit_mounts_in_userns=1'
  when: ansible_distribution == "Debian"
  tags:
    - modprobe
...
